port 1194
proto udp
dev tun

ca /home/mirai/vpn-infrastructure-project/server/ca.crt
cert /home/mirai/vpn-infrastructure-project/server/server.crt
key /home/mirai/vpn-infrastructure-project/server/server.key
dh /home/mirai/vpn-infrastructure-project/server/dh.pem

server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt

keepalive 10 120
cipher AES-256-GCM
user nobody
group nobody
persist-key
persist-tun

status openvpn-status.log
verb 3
explicit-exit-notify 1

tls-crypt /home/mirai/vpn-infrastructure-project/server/ta.key

key-direction 0

